TF-1360 Fix can not load new email until reload mail list
linagora/tmail-flutter pull request #1375
Opened 2023-01-04 06:09 UTC by dab246

#1360 

### Resolved

https://user-images.githubusercontent.com/80730648/210494397-1465d536-d401-4b90-9d59-993a5925ab2d.mp4

2023-01-05 02:25 UTC, nqhhdev approved these changes

2023-01-05 22:56 UTC, hoangdat requested changes
still waiting for better solution in handling empty stream

2023-01-06 07:57 UTC, hoangdat commented
@dab246 can you write the docs related to `streamController` in re-login case?

2023-01-06 08:33 UTC, dab246 commented
> @dab246 can you write the docs related to `streamController` in re-login case?

It's pretty simple, so I'll explain it here:
- When we do `logout`, call the function `closeStreamController` of fcm. So when `login` again we have not initialized `StreamController` because these objects are initialized in the `singleton` class.
- So the solution would be to re-initialize the `StreamController` when it is `closed` every time I login again

2023-01-06 10:11 UTC, sherlockvn submitted a review, later dismissed

2023-01-06 10:35 UTC, dab246 commented on lib/features/mailbox_dashboard/presentation/controller/mailbox_dashboard_controller.dart
> +  void _updateTheme() {
On android, `statusbar`, `bottombar` difference between screens. So we need change it when resume app from background

2023-01-09 07:44 UTC, hoangdat approved these changes

2023-01-09 07:44 UTC, merged