TF-2708 Allow Chrome to download PDF after view
linagora/tmail-flutter pull request #2711
Opened 2024-03-14 08:27 UTC by tddang-linagora

### Issue
- #2708 

### Demo

https://github.com/linagora/tmail-flutter/assets/160106668/35893c47-c8c1-4ede-bd13-217a87a76ffa

2024-03-14 08:48 UTC, chibenwa approved these changes

2024-03-14 08:52 UTC, dab246 approved these changes
lgtm

2024-03-15 02:00 UTC, hoangdat commented
we should go in option #2712

2024-03-15 02:01 UTC, hoangdat requested changes
keep it here if #2712 not work well in testing

2024-03-15 03:45 UTC, closed without merging