TF-2758 Email event description in html
linagora/tmail-flutter pull request #2762
Opened 2024-04-01 09:18 UTC by tddang-linagora

### Issue
- #2758 

### Before
![Screenshot 2024-04-01 at 16 12 43](https://github.com/linagora/tmail-flutter/assets/160106668/18ff5d1e-91e0-484a-9cc4-d4f73041ee83)
![Screenshot 2024-04-01 at 16 13 01](https://github.com/linagora/tmail-flutter/assets/160106668/1ffbb6d5-65f6-4bf7-af2c-8de3a1432db3)
### After
![Screenshot 2024-04-01 at 16 13 21](https://github.com/linagora/tmail-flutter/assets/160106668/81e2c365-8e8a-4abe-941c-6840bde5ed68)
![Screenshot 2024-04-01 at 16 13 41](https://github.com/linagora/tmail-flutter/assets/160106668/13aaa963-8ea7-4add-bd81-0f7c16c3b8d7)

2024-04-01 19:15 UTC, chibenwa commented
![image](https://github.com/linagora/tmail-flutter/assets/6928740/2bd9399c-fcb4-45a6-b3a1-3a0b0e04d734)

That's HTML in the event.

![image](https://github.com/linagora/tmail-flutter/assets/6928740/c783b372-e78e-4d23-93f0-71c7bab4be7b)

And that's HTML in the JMAP call too.

Please directly render HTML (after sanitizing) rather than passing through a plain text escaped representation.

2024-04-01 19:16 UTC, chibenwa requested changes
CF earlier comment

2024-04-02 02:32 UTC, hoangdat commented on core/lib/presentation/extensions/string_extension.dart
> +  }
did we have any HTML transformer?

2024-04-02 02:32 UTC, hoangdat commented on core/lib/presentation/extensions/string_extension.dart
> +  }
did we have any HTML transformer?

2024-04-02 03:03 UTC, tddang-linagora commented
> ![image](https://private-user-images.githubusercontent.com/6928740/318541708-2bd9399c-fcb4-45a6-b3a1-3a0b0e04d734.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjczMDIsIm5iZiI6MTcxMjAyNzAwMiwicGF0aCI6Ii82OTI4NzQwLzMxODU0MTcwOC0yYmQ5Mzk5Yy1mY2I0LTQ1YTYtYjNhMS0zYTBiMGUwNGQ3MzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDMwMzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjEwMGE4YjZiYTI1MWNiZWM2ZmZmNTk1OWMwOTRmN2MxOTQ1YzgxYjE0M2M5YzNkZGUyNjAxODZlZTBjN2NkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ixZhEedaQzFnZqzbYmFFL_IrXM4DeYcqY9awmwwkJWg)
> 
> That's HTML in the event.
> 
> ![image](https://private-user-images.githubusercontent.com/6928740/318542138-c783b372-e78e-4d23-93f0-71c7bab4be7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjczMDIsIm5iZiI6MTcxMjAyNzAwMiwicGF0aCI6Ii82OTI4NzQwLzMxODU0MjEzOC1jNzgzYjM3Mi1lNzhlLTRkMjMtOTNmMC03MWM3YmFiNGJlN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDMwMzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM5YzEwY2M3OGFlMGFiNzkzYzBjNWMwZjA5OGU1OGY1MDIyMjQ1NGQ1ZjIzM2E5ZWQwNmViNGNhYzllYTc0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iVa55vxm0yNheePBI3Pjr_I2yYHM3siZy54aKyspzss)
> 
> And that's HTML in the JMAP call too.
> 
> Please directly render HTML (after sanitizing) rather than passing through a plain text escaped representation.

Done

2024-04-03 07:17 UTC, hoangdat commented on core/lib/presentation/extensions/string_extension.dart
> +  }
how about using `TransformConfiguration` to handle html? WDYT @dab246

2024-04-12 04:30 UTC, dab246 approved these changes
lgtm

2024-04-12 04:42 UTC, hoangdat approved these changes

2024-04-12 04:42 UTC, merged